#!/usr/bin/python -i
# -*- coding: utf-8 -*-

import sys
import os

PIAMOD_HOME = os.getenv("PIAMOD_HOME")
if( PIAMOD_HOME == None ):
	print "### Error ###: Environment variable PIAMOD_HOME not found !!!"
	quit()

sys.path.append(PIAMOD_HOME+"/src")

from PIAMoD import *
PIAMoD.run()

